theme: minima
title: Your Site Title
description: A brief description of your site
baseurl: "/Site" # the subpath of your site, e.g. /blog
url: "https://grantparkinson-dev.github.io" # the base hostname & protocol for your site
github_username: grantparkinson-dev

# Build settings
markdown: kramdown
plugins:
  - jekyll-feed
  - jekyll-seo-tag

# Exclude files from processing
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock

include:
  - projects

collections:
  posts:
    output: true

defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"

# Generate posts.json
page_data:
  posts:
    json: 'blog/posts.json'